<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPcPdJaV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPcPdJaV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPcPdJaV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPcPdJaV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPcPdJaV\App_KernelDevDebugContainer([
    'container.build_hash' => 'PcPdJaV',
    'container.build_id' => '76e14943',
    'container.build_time' => 1650734073,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPcPdJaV');
